Nettbanken/Controllers/KundeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Windows;
using System.Web.Mvc;
using Nettbanken.BLL;
using Nettbanken.Models;
using Nettbanken.DAL;
using System.Threading;
using System.Windows.Forms;
using System.Timers;

namespace Nettbanken.Controllers
{  
    // KundeController, interaksjonene mellom model og view
    public class KundeController : Controller
    {
        private INettbankBLL _nettbankBLL;
        private Boolean harStartet;
        private new System.Timers.Timer timer1;

        // Konstruktør, relatert til stub/unittesting
        public KundeController()
        {
            _nettbankBLL = new NettbankBLL();
        }

        // Konstruktør, relatert til stub/unittesting
        public KundeController(INettbankBLL stub)
        {
            _nettbankBLL = stub;
        }

        // Returnerer forsiden til Nettbanken
        public ActionResult forsideView()
        {
            // Tester om det er data i databasen, hvis ikke opprettes dummydata
            _nettbankBLL.startsjekk();
            // Start transaksjon sjekkingen.
            transaksjonerStatusSjekking();

            // Kunde session
            // Sjekker om session finnes, hvis ikke så settes den
            if (Session["innlogget"] == null)
            {
                Session["innlogget"] = false;
            }

            // Admin Session
            // Sjekker om session finnes, hvis ikke så settes den
            if (Session["innloggetAdmin"] == null)
            {
                Session["innloggetAdmin"] = false;
            }

            return View();
        }

        // Side for registrering av kunde
        public ActionResult kundeRegistreringView()
        {
            return View();
        }

        // View som brukes når kunde registrer seg
        // Pga oppsett i view, så returnerer det et objekt av kunde.
        [HttpPost]
        public ActionResult kundeRegistreringView(Kunde kunde)
        {
            ModelState.Remove("bankId");
            if (ModelState.IsValid) //valider 
            {
                // Hvis registrering av kunde OK
                if (_nettbankBLL.registrerKunde(kunde))
                {
                    System.Windows.Forms.MessageBox.Show("Registrering godkjent! Ditt BankID er: " + Session["bankid"]);
                    return RedirectToAction("kundeLogginnView");
                }
            }

            return View();
        }

        // Innloggingsside for admins
        public ActionResult adminLogginnView()
        {
            if (Session["innloggetAdmin"] != null)
            {
                bool innlogget = (bool)Session["innloggetAdmin"];
                if (innlogget)
                {
                    return RedirectToAction("adminsideView");
                }
                return View();
            }

            return RedirectToAction("forsideView");
        }

        // Kundens innloggingsside
        public ActionResult kundeLogginnView()
        {
            if (Session["innlogget"] != null)
            { 
                bool innlogget = (bool)Session["innlogget"];
                if (innlogget)
                {
                    return RedirectToAction("hjemmesideView");
                }
                return View();
            }

            return RedirectToAction("forsideView");
        }

        // Viewet som brukes når admin prøver å logge seg inn
        [HttpPost]
        public ActionResult adminLogginnView(Admin admin)
        {
            // Property som ikke trenger vare med valideringen for innlogging
            ModelState.Remove("fornavn");
            ModelState.Remove("etternavn");
            ModelState.Remove("adresse");
            ModelState.Remove("telefonNr");
            ModelState.Remove("postNr");
            ModelState.Remove("poststed");

            if (ModelState.IsValid)
            {
                // Sjekker om logginn informasjon til admin er gyldig
                if (_nettbankBLL.adminLogginn(admin))
                {
                    // Hvis en logger seg inn som admin, så logges kundekonto ut dersom en kundekonto er innlogget
                    if((Boolean)Session["innlogget"])
                    {
                        Session["innlogget"] = false;
                        Session["personnr"] = null;
                        Session["bankid"] = null;
                        Session["kontoer"] = null;
                        Session["tempTabell"] = null;
                    }
                    Session["innloggetAdmin"] = true;

                    return RedirectToAction("adminsideView");
                }
            }

            Session["innloggetAdmin"] = false;
            return View();
        }

        // View som brukes når kunde prøver å logge inn
        [HttpPost]
        public ActionResult kundeLogginnView(Kunde kunde)
        {
            // Property som ikke trenger vare med valideringen for innlogging
            ModelState.Remove("fornavn");
            ModelState.Remove("etternavn");
            ModelState.Remove("adresse");
            ModelState.Remove("telefonNr");
            ModelState.Remove("postNr");
            ModelState.Remove("poststed");

            if (ModelState.IsValid) //Valider
            {
                // Sjekker om innloggingsinformasjoner gyldig
                if (_nettbankBLL.kundeLogginn(kunde)) 
                {
                    // Hvis en logger seg inn som kunde, så logges adminbruker ut dersom en adminbruker er innlogget
                    Session["innloggetAdmin"] = false;
                    Session["innlogget"] = true;

                    // Initialiserer betalingsListe, trenger en verdi hvis ikke gir det en error ved oppstart
                    var betalingsListe = new List<String[]>();
                    String[] temp = { "initializer" };
                    betalingsListe.Add(temp);

                    String personnr = kunde.personNr;
                    
                    // Lagrer nødvendig informasjon inn i sessions
                    Session["personnr"] = kunde.personNr;
                    Session["bankid"] = kunde.bankId;
                    Session["kontoer"] = _nettbankBLL.hentKontoer(personnr);
                    Session["tempTabell"] = betalingsListe;

                    return RedirectToAction("hjemmesideView");
                }
            }

            Session["innlogget"] = false;
            return View();
        }

        // Hjemmesiden til admins
        public ActionResult adminsideView()
        {
            // Siden kan kun vises dersom man er innlogget
            if (Session["innloggetAdmin"] != null)
            {
                bool innlogget = (bool)Session["innloggetAdmin"];

                if (innlogget)
                {
                    List<Kunde> alleKunder = _nettbankBLL.alleKunder();
                    return View(alleKunder);
                }
                return RedirectToAction("adminLogginnView");
            }

            return RedirectToAction("forsideView");
        }

        // Hjemmesiden til kunde etter suksessfull innlogging
        public ActionResult hjemmesideView()
        {
            // Siden kan kun vises dersom man er innlogget
            if (Session["innlogget"] != null)
            {
                bool innlogget = (bool)Session["innlogget"];
                if (innlogget)
                {
                    // Henter kontoer til gitt kunde
                    var kontoer = (List<String>)Session["kontoer"];
                    ViewBag.personnr = (String)Session["personnr"];

                    return View(kontoer);
                }
                return RedirectToAction("kundeLogginnView");
            }

            return RedirectToAction("forsideView");
        }

        // Siden for utføring av transaksjoner
        public ActionResult transaksjonView()
        {
            // Siden kan kun vises dersom man er innlogget
            if (Session["innlogget"] != null)
            {
                bool innlogget = (bool)Session["innlogget"];
                if (innlogget)
                {
                    ViewBag.personnr = (String)Session["personnr"];
                    ViewBag.kontoer = (List<String>)Session["kontoer"];

                    // Resetter betalingsliste om den har blitt brukt før
                    var betalingsListe = (List<String[]>)Session["tempTabell"];
                    if (betalingsListe.Count > 1)
                    {
                        betalingsListe.Clear(); //clear transaction buffer
                        String[] temp = { "initializer" };
                        betalingsListe.Add(temp);
                    }

                    Session["tempTabell"] = betalingsListe;

                    return View();
                }
                return RedirectToAction("kundeLogginnView");
            }

            return RedirectToAction("forsideView");
        }

        // Side som sletter en gitt kunde, brukes av admins
        public ActionResult slettView(string idnr)
        {
            // Kan kun aksesseres dersom man er innlogget som admin
            if (Session["innloggetAdmin"] != null)
            {
                bool innlogget = (bool)Session["innloggetAdmin"];
                if (innlogget)
                {
                    var kunden = _nettbankBLL.finnKunde(idnr);
                    return View(kunden);
                }
                return RedirectToAction("adminLogginnView");
            }

            return RedirectToAction("forsideView");
        }

        // Siden som endrer en gitt kunde, bruke av admins
        public ActionResult endreView(String idnr)
        {
            // Siden vises kun derso mman er logget inn som admin
            if (Session["innloggetAdmin"] != null)
            {
                bool innlogget = (bool)Session["innloggetAdmin"];
                if (innlogget)

Nettbanken/Views/Kunde/adminLogginnView.cshtml
@model Nettbanken.Models.Admin

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Admin Logginn</title>
    <link href="~/Content/logginn_register.css" rel="stylesheet" type="text/css">


</head>

<body>
    @using (Html.BeginForm("adminLogginnView", "Kunde", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <fieldset>
            <div class="row">
                <div class="header">
                    <div class="header-container">
                        <img src="~/Content/images/nettbanken.png" class="logo">
                    </div>

                    <div class="logginn-container">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="editor-lable">
                            @Html.LabelFor(model => model.adminId)
                        </div>
                        <div class="editor-field">
                            @Html.EditorFor(model => model.adminId)
                            @Html.ValidationMessageFor(model => model.adminId, "", new { @class = "text-danger" })
                        </div>
                        <div class="editor-lable">
                            @Html.LabelFor(model => model.passord)
                        </div>
                        <div class="editor-field">
                            @Html.PasswordFor(model => model.passord)
                            @Html.ValidationMessageFor(model => model.passord, "", new { @class = "text-danger" })
                        </div>
                        <br />
                        <div>
                            <button class="form-btn" type="submit" value="Logg inn">Logg inn</button>
                        </div>
                        <br/>
                        <p>Admin ID: 1</p> 
                        <p>Passord: ghettoadmin</p>

                    </div>

                    <div class="footer-container">
                        <div>
                            @Html.ActionLink("Tilbake til forside", "forsideView")
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    }
</body>

</html>

Nettbanken/Views/Kunde/adminsideView.cshtml
@model List<Nettbanken.Models.Kunde>

<html>
<head>
    <title>Nettbanken</title>
    <link href="~/Content/forside_bootstrap1.css" rel="stylesheet">
    <link href="~/Content/AdminView.css" rel="stylesheet">
</head>

<body>
    
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <img src="~/Content/images/nettbanken.png" width="200px">
            </div>
        </div>
        <!-- /bar end -->
        </div>
        <!-- /.container end -->
    </nav>

    <div id="panel">

        <div class="header">
            <div class="title"><a>Administrator</a></div>
        </div>

        <div class="Gull_farge">
            <ul></ul>
        </div>

        <div id="høyre_side">
            <div id="høyre_content">
                <h1 style="margin-top:2%;">Kunder</h1>


                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model[0].personNr)
                           
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model[0].fornavn)

                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model[0].etternavn)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model[0].adresse)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model[0].postNr)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model[0].poststed)
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.personNr)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.fornavn)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.etternavn)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.adresse)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.postNr)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.poststed)
                            </td>
                            <td>
                                @Html.ActionLink("Endre", "endreView", new { idnr = item.personNr }, new { @class = "btn btn-success" })
                                @Html.ActionLink("Info", "infoView", new { idnr = item.personNr }, new { @class = "btn btn-primary" })
                                @Html.ActionLink("Slette", "slettView", new { idnr = item.personNr }, new { @class = "btn btn-danger" })
                            </td>
                        </tr>
                    }

                </table>
                @Html.ActionLink("Registrer ny Kunde", "registrerViaAdmin", new { tom = "" }, new { @class = "btn btn-success" })
                <input type="button" class="btn btn-danger" value="Logg ut" onclick="location.href='@Url.Action("loggUt","Kunde")'" />
                <div class="knapper_under_panel">
                </div>


            </div>
        </div><!-- end of right content-->


        <div class="clear"></div>
    </div> <!--end of center_content-->
</body>
</html>

Nettbanken/Views/Kunde/hjemmesideView.cshtml
@model List<string>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Hjemmeside</title>
    <script src="~/scripts/jquery-3.1.1.js"></script>
    <script src="~/scripts/jquery.unobtrusive-ajax.js"></script>
    <link href="~/Content/innlogget_bootstrap.css" rel="stylesheet" type="text/css">
    <link href="~/Content/kundeside.css" rel="stylesheet" type="text/css">

    <script type="text/javascript">
        // Metode som oppdaterer tabell med korrekt info
        function printUtskrift()
        {
            $("#kontoInformasjon").load("/Kunde/hentKontoInformasjon", { kontonavn: $("#kontoDropdown").val(), personnr: @ViewBag.personnr });
            $("#kontoUtskrift").load("/Kunde/hentKontoUtskrift", { kontonavn: $("#kontoDropdown").val(), personnr: @ViewBag.personnr });
        }
        $(document).ready(function () {
            $("#kontoInformasjon").load("/Kunde/hentKontoInformasjon", { kontonavn: $("#kontoDropdown").val(), personnr: @ViewBag.personnr });
            $("#kontoUtskrift").load("/Kunde/hentKontoUtskrift", { kontonavn: $("#kontoDropdown").val(), personnr: @ViewBag.personnr });
        });
    </script>
</head>

<body>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <img src="~/Content/images/nettbanken.png" width="200px">
            </div>
        </div>
        
        <div style="margin-left:75%; margin-top:-4%;">
            <button type="button" class="btn btn-default btn-sm" onclick="location.href='@Url.Action("transaksjonView","Kunde")'">
                <span class="glyphicon glyphicon-credit-card"></span> Transaksjoner
            </button>
        </div>
        <div style="margin-left:89%; margin-top:-3%;">
            <button type="button" class="btn btn-default btn-sm" onclick="location.href='@Url.Action("loggUt","Kunde")'">
            <span class="glyphicon glyphicon-log-out"></span> Logg Ut
            </button>
        </div>
    </nav>

    <div id="panel">

        <div class="header">
            <div class="title"><a>Kunde</a></div>
        </div>

        <div class="Gull_farge">
            <ul></ul>
        </div>
        <span style="font-size:10px;color:red">
            <b>NB!</b>
            <b>Påminnelse din BankID er: @Session["bankid"]</b>
        </span>
        <div id="høyre_side">
            <div id="høyre_content">
                <h1>Konto oversikt</h1>
                <!--<h1>Velg konto:</h1>-->
                
                <p style="margin-top:2%;"><b>Velg Konto:</b>
                <select id="kontoDropdown" onchange="printUtskrift()" style="margin-left:2%;">
                    @foreach (var konto in Model)
                     {
                       <option>@konto</option>
                      }
                </select>
                </p>
                <hr>


            </div>
        </div>
        <br />

        <div class="container">

            <!--<input type="button" class="btn btn-primary" value="Utskrift" onclick="printUtskrift()"/>-->
        </div>

        <div id="kontoInformasjon" style="margin-left:1%; margin-right:1%;">
            <!--Her kommer konto informasjon-->
        </div>
        <br />
        <hr>
        <div id="kontoUtskrift" style="margin-left:1%; margin-right:1%;">
            <!--Her kommer utskriftstabellen-->
        </div>
        <hr>
        <div class="knapper_under_panel">
        </div>
    </div>
    <div class="clear"></div>
</body>

</html>

Nettbanken/Views/Kunde/info.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    
    </div>
</body>
</html>

Nettbanken/Views/Kunde/kundeLogginnView.cshtml
@model Nettbanken.Models.Kunde

<!DOCTYPE html>

<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Kunde Logginn</title>
        <link href="~/Content/logginn_register.css" rel="stylesheet" type="text/css">


    </head>

    <body>
        @using (Html.BeginForm("kundeLogginnView", "Kunde", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <fieldset>
                <div class="row">
                    <div class="header">
                        <div class="header-container">
                            <img src="~/Content/images/nettbanken.png" class="logo">
                        </div>

                        <div class="logginn-container">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="editor-lable">
                                @Html.LabelFor(model => model.bankId)
                            </div>
                            <div class="editor-field">
                                @Html.EditorFor(model => model.bankId)
                                @Html.ValidationMessageFor(model => model.bankId, "", new { @class = "text-danger" })
                            </div>
                            <div class="editor-lable">
                                @Html.LabelFor(model => model.personNr)
                            </div>
                            <div class="editor-field">
                                @Html.EditorFor(model => model.personNr)
                                @Html.ValidationMessageFor(model => model.personNr, "", new { @class = "text-danger" })
                            </div>
                            <div class="editor-lable">
                                @Html.LabelFor(model => model.passord)
                            </div>
                            <div class="editor-field">
                                @Html.PasswordFor(model => model.passord)
                                @Html.ValidationMessageFor(model => model.passord, "", new { @class = "text-danger" })
                            </div>
                            <br/>
                            <div>
                                <button class="form-btn" type="submit" value="Logg inn">Logg inn</button>
                            </div>
                            <br/>
                            <p>Per Bakke</p>
                            <p>Bank ID = 1</p>
                            <p>Personnummer = 118921160<p/>
                            <p>Passord = passord</p>

                         </div>

                            <div class="footer-container">
                                <div>
                                    @Html.ActionLink("Tilbake til forside", "forsideView")
                                </div>
                            </div>
                        </div>
                    </div>
             </fieldset>
        }
    </body>

</html>

Nettbanken/Views/Kunde/kundeRegistreringView.cshtml
@model Nettbanken.Models.Kunde

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Kunde Register</title>
    <link href="~/Content/logginn_register.css" rel="stylesheet" type="text/css">
</head>

    <body>
        <!--BeginForm har parameterene (metodenavn, kontrollernavn, postmethod)-->
        @using (Html.BeginForm("kundeRegistreringView", "Kunde", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="row">
                <div class="header">
                    <div class="header-container">
                        <img src="~/Content/images/nettbanken.png" class="logo">
                    </div>

                    <div class="logginn-container">

                        <fieldset>
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="editor-lable">
                                @Html.LabelFor(model => model.personNr)
                            </div>
                            <div class="editor-field">
                                @Html.EditorFor(model => model.personNr)
                                @Html.ValidationMessageFor(model => model.personNr, "", new { @class = "text-danger" })
                            </div>
                            <div class="editor-lable">
                                @Html.LabelFor(model => model.passord)
                            </div>
                            <div class="editor-field">
                                @Html.PasswordFor(model => model.passord)
                                @Html.ValidationMessageFor(model => model.passord, "", new { @class = "text-danger" })
                            </div>
                            <div class="editor-lable">
                                @Html.LabelFor(model => model.fornavn)
                            </div>
                            <div class="editor-field">
                                @Html.EditorFor(model => model.fornavn)
                                @Html.ValidationMessageFor(model => model.fornavn, "", new { @class = "text-danger" })
                            </div>
                            <div class="editor-lable">
                                @Html.LabelFor(model => model.etternavn)
                            </div>
                            <div class="editor-field">
                                @Html.EditorFor(model => model.etternavn)
                                @Html.ValidationMessageFor(model => model.etternavn, "", new { @class = "text-danger" })
                            </div>
                            <div class="editor-lable">
                                @Html.LabelFor(model => model.adresse)
                            </div>
                            <div class="editor-field">
                                @Html.EditorFor(model => model.adresse)
                                @Html.ValidationMessageFor(model => model.adresse, "", new { @class = "text-danger" })
                            </div>
                            <div class="editor-lable">
                                @Html.LabelFor(model => model.telefonNr)
                            </div>
                            <div class="editor-field">
                                @Html.EditorFor(model => model.telefonNr)
                                @Html.ValidationMessageFor(model => model.telefonNr, "", new { @class = "text-danger" })
                            </div>
                            <div class="editor-lable">
                                @Html.LabelFor(model => model.postNr)
                            </div>
                            <div class="editor-field">
                                @Html.EditorFor(model => model.postNr)
                                @Html.ValidationMessageFor(model => model.postNr, "", new { @class = "text-danger" })
                            </div>
                            <div class="editor-lable">
                                @Html.LabelFor(model => model.poststed)
                            </div>
                            <div class="editor-field">
                                @Html.EditorFor(model => model.poststed)
                                @Html.ValidationMessageFor(model => model.poststed, "", new { @class = "text-danger" })
                            </div>

                            <br />
                            <div>
                                <button class="form-btn" type="submit" value="Registrer">Register</button>
                            </div>
                        </fieldset>

                    </div>
                    <div class="footer-container">
                        <div>
                            @Html.ActionLink("Tilbake til forside", "forsideView")
                        </div>
                    </div>
                </div>
            </div>
        }
    </body>

</html>

Nettbanken/Views/Kunde/slett.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    
    </div>
</body>
</html>

Nettbanken/Views/Kunde/slettView.cshtml
@model Nettbanken.Models.Kunde

<!DOCTYPE html>

<html>
<head>
    <title>Nettbanken</title>
    <link href="~/Content/forside_bootstrap1.css" rel="stylesheet">
    <link href="~/Content/AdminEndreView.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <img src="~/Content/images/nettbanken.png" width="200px">
            </div>
        </div>
        <!-- /bar end -->
        <!-- /.container end -->
    </nav>
    <br /><br />
    <div id="panel" style="padding-bottom:27%;">

        <div class="header">
            <div class="title"><a>Administrator</a></div>
        </div>

        <div class="Gull_farge">
            <ul></ul>
        </div>
        <div id="høyre_side">
            <div id="høyre_content">
                <h1 style="margin-top:2%;">Kunde</h1>
                <h3>Er du sikker på at du vil slette denne?</h3>
                <div>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.personNr)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.personNr)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.fornavn)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.fornavn)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.etternavn)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.etternavn)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.adresse)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.adresse)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.postNr)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.postNr)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.poststed)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.poststed)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.telefonNr)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.telefonNr)
                        </dd>
                    </dl>
                    <hr />
                </div>
            </div>
        </div>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-actions no-color" style="margin-left: 8%;">
                <button id="slettKunde" class="btn btn-danger" type="button" value="Registrer" onclick="location.href='@Url.Action("slettEnKundeFraDB","Kunde",new { idnr = @Html.DisplayFor(model => model.personNr)} )'">Slett</button>
                <button id="slettKunde" class="btn btn-primary" type="button" onclick="location.href='@Url.Action("adminsideView","Kunde")'">Tilbake</button>
            </div>
        }
    </div>

</body>
</html>